# Generated by Django 5.0.6 on 2024-06-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jaatelokioski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='firma', max_length=50)),
                ('kontakti', models.CharField(default='firma', max_length=50)),
                ('osoite', models.CharField(default='firma', max_length=100)),
                ('puhelinnumero', models.CharField(default='firma', max_length=20)),
                ('sahkopostiosoite', models.CharField(default='firma', max_length=50)),
                ('maa', models.CharField(default='firma', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuotenimi', models.CharField(default='banaanijaatelo', max_length=20)),
                ('pakkauskoko', models.CharField(default=3, max_length=20)),
                ('hinta', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('varastomaara', models.IntegerField(default=3)),
                ('jaatelokioski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jaatelokioski')),
            ],
        ),
    ]
